### ISSUE TITLE
It doesn't compile

### ISSUE THREAD

**Issue by cibersheep** [dschwen/jszip#1]
Trying to compile gives these errors:
```
WARNING  root: emcc: cannot find library "z"
WARNING  root: emcc: cannot find library "termcap"
WARNING  root: Assigning a non-existent settings attribute "USE_ZLIB"
WARNING  root:  - did you mean one of USE_BSS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
```

**Comment by dschwen** [comment]
Yeah, I think I fixed those. I'll push my branch later . The cost was developed with a very early emscripten version. The main issue us that the EM_ASM macro syntax changed completely. I was working on that just yesterday.

**Comment by cibersheep** [comment]
Ouh. That sounds exiting.
I'll wait patiently :D 
Cheers!

**Comment by dschwen** [comment]
Btw. what system are you trying to build on and which emscripten version are you using?

**Comment by cibersheep** [comment]
I'm on Ubuntu 16.04 and emscripten 1.22.1
Edit: I had «installed» emscripten 1.36.0. Now updating to 1.37.29.

**Comment by dschwen** [comment]
Yeah, I get the same errors you report on 1.22.1 and cannot find a solution for fixing them.
It is really annoying that emscripten is such a moving target. Check out 1.37.x, it is what I have on my other machine. That version has the radically changed EM_ASM.
I think at this point I need help. I'm really annoyed that I didn't commit a compiled JS version back when it built...

**Comment by cibersheep** [comment]
I see. Emscripten is really confuse for me. I had tried to do several things and «died»
Do you remember what version was compiling the code?
There's older codes: https://github.com/kripken/emscripten/releases?after=1.21.1
And older portable emsdk: https://github.com/juj/emsdk

Oh, also:
«You can always install old SDK and compiler toolchains via the latest emsdk. If you need to fall back to an old version, download the Portable SDK version and use that to install a previous version of a tool. All old tool versions are available by typing `emsdk list --old`.»

**Comment by dschwen** [comment]
I'll try installing an old emscripten. That's a good idea. I used whatever was the version in Dec 2013.

**Comment by dschwen** [comment]
Whoahhh!!!! I followed your suggestion and installed emscripten-1.8.2 and it _works_! e2edeeee
I needed to manually set the correct `LLVM_ROOT` in `.emscripten` but then it just built without a hitch. I haven't done any testing yet though. But it is at least a great first step.

**Comment by dschwen** [comment]
Tested and works!

**Comment by cibersheep** [comment]
I'm glad you got it working. I know the feeling :)
It's a bit offtopic but I spent two days to try to get virtual keyboards sending character keydown to Quixe... and I just got a solution.

**Comment by dschwen** [comment]
Thanks for prodding me! I'll update the repo accordingly tomorrow.

**Comment by cibersheep** [comment]
Thank you for taking the time to compile it... it looks great!

**Comment by cibersheep** [comment]
Ouh! This is soooo cool!
![imatge](https://user-images.githubusercontent.com/6640041/35546580-16881dbc-0575-11e8-9713-7d5f16c60073.png)

**Comment by dschwen** [comment]
Does the automap work for that game?

**Comment by cibersheep** [comment]
Not for Star Trek XD but it works in any otjer I tried. And that'a an even cooler feature

**Comment by dschwen** [comment]
Alrighty. I added build instructions to the README and updated Travis-CI config. Build passes now. I think we can close the issue! 🙌
